apiVersion: apps/v1
kind: Deployment
metadata:
  name: Argo-deployment
  labels:
    app: abhisheksawant10/test-argocd-helloworld1:latest
spec:
  selector:
    matchLabels:
      app: abhisheksawant10/test-argocd-helloworld1:latest
  replicas: 1
  template:
    metadata:
      labels:
        app: abhisheksawant10/test-argocd-helloworld1:latest
    spec:
      containers:
      - name: Argo-test
        image: abhisheksawant10/test-argocd-helloworld1:latest
        ports:
        - containerPort: 80
