apiVersion: v1
kind: Service
metadata:
 name: service
 labels:
   app: abhisheksawant10/test-argocd-helloworld1:latest
spec:
  selector:
    app: abhisheksawant10/test-argocd-helloworld1:latest
  type: NodePort
  ports:
  - nodePort: 30083
    port: 80
    targetPort: 80
