apiVersion: v1
kind: Service
metadata:
 name: argocd-svc 
 labels:
   app: test-argocd-helloworld1
spec:
  selector:
    app: test-argocd-helloworld1
  type: NodePort
  ports:
  - nodePort: 30083
    port: 80
    targetPort: 80
