
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Snyk latest CLI
      run: |
         npm install snyk -g
         snyk --version
    - name: Snyk test command
      run: |
         ls -la
         snyk auth ${{ secrets.SNYK_TOKEN }}
         snyk test
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Maven package 
      run: |
        cd target
        ls -a
 
 
 
      
  

    
